# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ErinMyLungs.github.io/cnn_oc_svm/"

git_url = "https://github.com/ErinMyLungs/cnn_oc_svm/tree/master/"

def custom_doc_links(name): return None
