# AUTOGENERATED! DO NOT EDIT! File to edit: 00_cnn_oc_svm.ipynb (unless otherwise specified).

__all__ = ['cnn_oc_svm']

# Cell
class cnn_oc_svm:
    """
    The base-class with simple CNN and OC-SVM.
    """
    pass